create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  sort_order numeric not null default 0,
  platform text not null,
  asset_type text not null,
  name text not null,
  ticker text default '',
  fund_code text default '',
  fund_pattern text default '',
  currency text not null default 'TWD',
  original_units numeric not null default 0,
  units numeric not null default 0,
  corporate_action text default '',
  avg_cost numeric not null default 0,
  total_cost_input numeric not null default 0,
  monthly_dividend_per_unit numeric not null default 0,
  purchase_ym text default '',
  dividend_received_original_total numeric not null default 0,
  dividend_received_total numeric not null default 0,
  dividend_note text default '',
  dividend_pay_date text default '',
  is_reinvest boolean not null default false,
  note text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.positions
add column if not exists sort_order numeric default 0,
add column if not exists original_units numeric default 0,
add column if not exists corporate_action text default '',
add column if not exists total_cost_input numeric default 0,
add column if not exists purchase_ym text default '',
add column if not exists dividend_received_original_total numeric default 0,
add column if not exists dividend_received_total numeric default 0,
add column if not exists dividend_note text default '',
add column if not exists dividend_pay_date text default '',
add column if not exists is_reinvest boolean default false;

alter table public.positions enable row level security;

drop policy if exists "anon read positions" on public.positions;
drop policy if exists "anon insert positions" on public.positions;
drop policy if exists "anon update positions" on public.positions;
drop policy if exists "anon delete positions" on public.positions;

create policy "anon read positions"
on public.positions for select
to anon
using (true);

create policy "anon insert positions"
on public.positions for insert
to anon
with check (true);

create policy "anon update positions"
on public.positions for update
to anon
using (true)
with check (true);

create policy "anon delete positions"
on public.positions for delete
to anon
using (true);

create table if not exists public.fund_dividends (
  id bigint generated by default as identity primary key,
  fund_code text not null,
  fund_name text default '',
  platform text default '',
  currency text default 'TWD',
  ex_date text not null,
  pay_date text default '',
  is_paid boolean not null default false,
  units_at_ex numeric not null default 0,
  div_amount numeric not null default 0,
  actual_div_amount numeric not null default 0,
  fx_rate numeric not null default 1,
  twd_total numeric not null default 0,
  note text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(fund_code, platform, currency, ex_date)
);

create table if not exists public.dividend_log (
  id bigint generated by default as identity primary key,
  logged_at timestamptz default now(),
  fund_code text not null,
  fund_name text default '',
  platform text default '',
  currency text default 'TWD',
  ex_date text default '',
  pay_date text default '',
  div_amount numeric not null default 0,
  actual_div_amount numeric not null default 0,
  units_at_ex numeric not null default 0,
  fx_rate numeric not null default 1,
  twd_total numeric not null default 0,
  is_paid boolean not null default false,
  note text default ''
);

alter table public.fund_dividends
add column if not exists fund_name text default '',
add column if not exists actual_div_amount numeric default 0;

alter table public.dividend_log
add column if not exists fund_name text default '',
add column if not exists actual_div_amount numeric default 0;

create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_at timestamptz default now(),
  total_twd numeric not null default 0,
  tw_stock numeric not null default 0,
  us_stock numeric not null default 0,
  kifutong numeric not null default 0,
  scb numeric not null default 0,
  taishin numeric not null default 0,
  total_cost numeric not null default 0,
  total_pnl numeric not null default 0,
  cumulative_dividend numeric not null default 0,
  trigger text default '',
  note text default ''
);

alter table public.fund_dividends enable row level security;
alter table public.dividend_log enable row level security;
alter table public.portfolio_snapshots enable row level security;

drop policy if exists "anon all fund_dividends" on public.fund_dividends;
drop policy if exists "anon all dividend_log" on public.dividend_log;
drop policy if exists "anon all portfolio_snapshots" on public.portfolio_snapshots;

create policy "anon all fund_dividends"
on public.fund_dividends for all
to anon
using (true)
with check (true);

create policy "anon all dividend_log"
on public.dividend_log for all
to anon
using (true)
with check (true);

create policy "anon all portfolio_snapshots"
on public.portfolio_snapshots for all
to anon
using (true)
with check (true);
