create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  platform text not null,
  asset_type text not null,
  name text not null,
  ticker text default '',
  fund_code text default '',
  fund_pattern text default '',
  currency text not null default 'TWD',
  units numeric not null default 0,
  avg_cost numeric not null default 0,
  monthly_dividend_per_unit numeric not null default 0,
  note text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.positions enable row level security;

drop policy if exists "anon read positions" on public.positions;
drop policy if exists "anon insert positions" on public.positions;
drop policy if exists "anon update positions" on public.positions;
drop policy if exists "anon delete positions" on public.positions;

create policy "anon read positions"
on public.positions for select
to anon
using (true);

create policy "anon insert positions"
on public.positions for insert
to anon
with check (true);

create policy "anon update positions"
on public.positions for update
to anon
using (true)
with check (true);

create policy "anon delete positions"
on public.positions for delete
to anon
using (true);
