create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  sort_order numeric not null default 0,
  platform text not null,
  asset_type text not null,
  name text not null,
  ticker text default '',
  fund_code text default '',
  fund_pattern text default '',
  currency text not null default 'TWD',
  original_units numeric not null default 0,
  units numeric not null default 0,
  corporate_action text default '',
  avg_cost numeric not null default 0,
  total_cost_input numeric not null default 0,
  monthly_dividend_per_unit numeric not null default 0,
  purchase_ym text default '',
  dividend_received_total numeric not null default 0,
  dividend_note text default '',
  note text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.positions
add column if not exists sort_order numeric default 0,
add column if not exists original_units numeric default 0,
add column if not exists corporate_action text default '',
add column if not exists total_cost_input numeric default 0,
add column if not exists purchase_ym text default '',
add column if not exists dividend_received_total numeric default 0,
add column if not exists dividend_note text default '';

alter table public.positions enable row level security;

drop policy if exists "anon read positions" on public.positions;
drop policy if exists "anon insert positions" on public.positions;
drop policy if exists "anon update positions" on public.positions;
drop policy if exists "anon delete positions" on public.positions;

create policy "anon read positions"
on public.positions for select
to anon
using (true);

create policy "anon insert positions"
on public.positions for insert
to anon
with check (true);

create policy "anon update positions"
on public.positions for update
to anon
using (true)
with check (true);

create policy "anon delete positions"
on public.positions for delete
to anon
using (true);
